-- PROJETO: ZENO-X MEI
-- VERSIONAMENTO DO BANCO DE DADOS
-- VERSÃO: 0001

ALTER TABLE PRODUTOS
	ADD COLUMN ID_CATEGORIA INT,
    ADD CONSTRAINT FK_PRODUTOS_CATEGORIAS
		FOREIGN KEY (ID_CATEGORIA)
        REFERENCES CATEGORIA_DETALHE(ID_CATEGORIA_DETALHE),
	ADD COLUMN SN_ATIVO BOOLEAN;

ALTER TABLE PRODUTO_ESTOQUE
	ADD COLUMN MED_CUSTO	DECIMAL(10,2) NOT NULL	,
    ADD COLUMN MAX_CUSTO	DECIMAL(10,2) NOT NULL	,
    ADD COLUMN MIN_PRECO	DECIMAL(10,2) NOT NULL	,
    ADD COLUMN MED_PRECO	DECIMAL(10,2) NOT NULL	;

CREATE TABLE PRODUTO_MATERIAL (
	ID_PRODUTO_MATERIAL		INT PRIMARY KEY AUTO_INCREMENT		,
    ID_PRODUTO				INT NOT NULL						,
    DT_MATERIAL				DATE NOT NULL						,
    ID_MATERIAL				INT NOT NULL						,
    DS_MATERIAL				VARCHAR(50)							,
    QT_MATERIAL				DECIMAL(10,3) NOT NULL				,
    SN_ATIVO				BOOLEAN NOT NULL					,
    ID_ENTIDADE				INT NOT NULL						,
    
	FOREIGN KEY (ID_PRODUTO) 	REFERENCES PRODUTOS(ID_PRODUTO)		,
    FOREIGN KEY (ID_MATERIAL) 	REFERENCES PRODUTOS(ID_PRODUTO)		,
    FOREIGN KEY (ID_ENTIDADE)	REFERENCES ENTIDADES(ID_ENTIDADE)	,
    
    CONSTRAINT CD_MATERIAL UNIQUE (DT_MATERIAL, ID_MATERIAL, ID_PRODUTO)
);

ALTER TABLE ESTOQUE
	ADD COLUMN ID_CONTRATO INT,
    ADD CONSTRAINT FK_ESTOQUE_CONTRATOS
		FOREIGN KEY (ID_CONTRATO) REFERENCES
		CONTRATOS(ID_CONTRATO),
	ADD COLUMN CD_ESTOQUE INT NOT NULL,
    ADD CONSTRAINT CD_ESTOQUE
		UNIQUE (ID_ENTIDADE, CD_ESTOQUE),
	DROP COLUMN CD_METODO,
    DROP CONSTRAINT ESTOQUE_ibfk_3,
    DROP COLUMN ID_CONTA;
    
ALTER TABLE ESTOQUE_ITENS
	ADD COLUMN CD_ITENS INT NOT NULL,
    ADD CONSTRAINT CD_ITENS
		UNIQUE (ID_ESTOQUE, CD_ITENS);
        
ALTER TABLE FINANCEIRO
	ADD COLUMN DOC_FINANCEIRO VARCHAR(50),
	ADD COLUMN CD_FINANCEIRO INT NOT NULL,
    ADD CONSTRAINT CD_FINANCEIRO
		UNIQUE (ID_ENTIDADE, CD_FINANCEIRO),
	DROP COLUMN CD_METODO,
    DROP CONSTRAINT FINANCEIRO_ibfk_5,
    DROP COLUMN ID_CONTA;
    
ALTER TABLE FINANCEIRO_DOCUMENTOS
	DROP COLUMN ANEXO,
    DROP COLUMN SN_ANEXO;

ALTER TABLE MOVIMENTACOES
	ADD COLUMN CD_MOVIMENTACAO INT NOT NULL,
    ADD CONSTRAINT CD_MOVIMENTACAO UNIQUE (ID_ENTIDADE, CD_MOVIMENTACAO),
    DROP COLUMN CD_METODO,
    DROP CONSTRAINT MOVIMENTACOES_ibfk_4,
    DROP COLUMN ID_CONTA,
    ADD COLUMN DOC_MOVIMENTACAO VARCHAR(50);
    
ALTER TABLE MOVIMENTACOES_ITENS
	ADD COLUMN CD_ITENS INT NOT NULL,
    ADD CONSTRAINT CD_ITENS UNIQUE (ID_MOVIMENTACAO, CD_ITENS);	
    
ALTER TABLE PESSOAS
	ADD COLUMN CON_CELULAR VARCHAR(11),
    ADD COLUMN CON_TELEFONE VARCHAR(11),
    ADD COLUMN CON_EMAIL VARCHAR(100),
	DROP COLUMN END_CIDADE,
    ADD COLUMN ID_CIDADE INT,
    ADD CONSTRAINT FK_PESSOAS_CIDADES
		FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES(ID_CIDADE);

ALTER TABLE CONTAS
	ADD COLUMN ID_CIDADE INT,
    ADD CONSTRAINT FK_CONTAS_PESSOAS
		FOREIGN KEY (ID_CIDADE) REFERENCES CIDADES(ID_CIDADE);