const ORDEM_SERVICO = (ID_ENTIDADE) => `
SELECT
    M.ID_MOVIMENTACAO AS ID,
    CONCAT(M.CD_MOVIMENTACAO, ' - ', P.NM_PESSOA) AS DS
FROM MOVIMENTACOES M
    INNER JOIN PESSOAS P ON M.ID_PESSOA = P.ID_PESSOA
WHERE M.ID_ENTIDADE = ${ID_ENTIDADE} AND M.TP_MOVIMENTACAO = 'O'
`

module.exports = {
    ORDEM_SERVICO
}