
const CIDADES = (ID_ENTIDADE) => `SELECT ID_CIDADE AS ID, CONCAT(NM_CIDADE, ' - ', UF_CIDADE) AS DS FROM CIDADES ORDER BY UF_CIDADE, NM_CIDADE`

const PESSOAS = (ID_ENTIDADE) => `
SELECT
    ID_PESSOA AS ID,
    CONCAT(CD_PESSOA, ' - ', NM_PESSOA, ' - ', CADASTRO) AS DS
FROM PESSOAS
    WHERE ID_ENTIDADE = ${ID_ENTIDADE}
    AND SN_ATIVO = 1
ORDER BY CD_PESSOA`

const CATEGORIAS_PRODUTOS = (ID_ENTIDAED) => `
SELECT
    CD.ID_CATEGORIA_DETALHE AS ID,
    CONCAT(C.CD_CATEGORIA, '.', CD.CD_DETALHE, ' - ', NM_DETALHE) AS DS
FROM CATEGORIA_DETALHE CD
    INNER JOIN CATEGORIAS C ON CD.ID_CATEGORIA = C.ID_CATEGORIA
WHERE C.ID_ENTIDADE = ${ID_ENTIDAED} AND C.TP_CATEGORIA = 'P'
    AND CD.SN_ATIVO = 1 AND C.SN_ATIVO = 1
ORDER BY CD_CATEGORIA, CD_DETALHE
`

const CATEGORIAS_ESTOQUE = (ID_ENTIDAED) => `
SELECT
    CD.ID_CATEGORIA_DETALHE AS ID,
    CONCAT(C.CD_CATEGORIA, '.', CD.CD_DETALHE, ' - ', NM_DETALHE) AS DS
FROM CATEGORIA_DETALHE CD
    INNER JOIN CATEGORIAS C ON CD.ID_CATEGORIA = C.ID_CATEGORIA
WHERE C.ID_ENTIDADE = ${ID_ENTIDAED} AND C.TP_CATEGORIA = 'E'
    AND CD.SN_ATIVO = 1 AND C.SN_ATIVO = 1
ORDER BY CD_CATEGORIA, CD_DETALHE
`

const CATEGORIA_FINANCEIRO = (ID_ENTIDAED) => `
SELECT
    CD.ID_CATEGORIA_DETALHE AS ID,
    CONCAT(C.CD_CATEGORIA, '.', CD.CD_DETALHE, ' - ', NM_DETALHE) AS DS
FROM CATEGORIA_DETALHE CD
    INNER JOIN CATEGORIAS C ON CD.ID_CATEGORIA = C.ID_CATEGORIA
WHERE C.ID_ENTIDADE = ${ID_ENTIDAED} AND C.TP_CATEGORIA = 'F'
    AND CD.SN_ATIVO = 1 AND C.SN_ATIVO = 1
ORDER BY CD_CATEGORIA, CD_DETALHE
`

const CATEGORIA_MOVIMENTACAO = (ID_ENTIDAED) => `
SELECT
    CD.ID_CATEGORIA_DETALHE AS ID,
    CONCAT(C.CD_CATEGORIA, '.', CD.CD_DETALHE, ' - ', NM_DETALHE) AS DS
FROM CATEGORIA_DETALHE CD
    INNER JOIN CATEGORIAS C ON CD.ID_CATEGORIA = C.ID_CATEGORIA
WHERE C.ID_ENTIDADE = ${ID_ENTIDAED} AND C.TP_CATEGORIA = 'M'
    AND CD.SN_ATIVO = 1 AND C.SN_ATIVO = 1
ORDER BY CD_CATEGORIA, CD_DETALHE
`

const PRODUTOS_MATERIAL = (ID_ENTIDADE) => `
SELECT
    ID_PRODUTO AS ID,
    CONCAT(CD_PRODUTO, ' - ', NM_PRODUTO) AS DS
FROM PRODUTOS
    WHERE ID_ENTIDADE = ${ID_ENTIDADE}
    AND TP_PRODUTO = 'M' AND SN_ATIVO = 1
ORDER BY CD_PRODUTO
`

const PRODUTOS_ESTOQUE = (ID_ENTIDADE) => `
SELECT
    P.ID_PRODUTO AS ID,
    CONCAT(P.CD_PRODUTO, ' - ', P.NM_PRODUTO) AS DS,
    P.UN_MEDIDA,
    PE.MED_CUSTO AS VL_UNITARIO
FROM PRODUTOS P
    LEFT JOIN (
		SELECT PE2.ID_PRODUTO,
        MAX(PE2.DT_INICIO) AS DT_INICIO
        FROM PRODUTO_ESTOQUE PE2
        GROUP BY 1
	) T ON T.ID_PRODUTO = P.ID_PRODUTO
    
	LEFT JOIN PRODUTO_ESTOQUE PE ON (P.ID_PRODUTO = PE.ID_PRODUTO AND T.DT_INICIO = PE.DT_INICIO)
    WHERE P.ID_ENTIDADE = ${ID_ENTIDADE}
    AND TP_PRODUTO IN ('M','P') AND SN_ATIVO = 1
ORDER BY CD_PRODUTO
`

const PRODUTOS_MOVIMENTACAO = (ID_ENTIDADE) => `
SELECT
    P.ID_PRODUTO AS ID,
    CONCAT(P.CD_PRODUTO, ' - ', P.NM_PRODUTO) AS DS,
    P.UN_MEDIDA,
    PE.MED_PRECO AS VL_UNITARIO
FROM PRODUTOS P
    LEFT JOIN (
		SELECT PE2.ID_PRODUTO,
        MAX(PE2.DT_INICIO) AS DT_INICIO
        FROM PRODUTO_ESTOQUE PE2
        GROUP BY 1
	) T ON T.ID_PRODUTO = P.ID_PRODUTO
    
	LEFT JOIN PRODUTO_ESTOQUE PE ON (P.ID_PRODUTO = PE.ID_PRODUTO AND T.DT_INICIO = PE.DT_INICIO)
    WHERE P.ID_ENTIDADE = ${ID_ENTIDADE}
    AND TP_PRODUTO IN ('S','P') AND SN_ATIVO = 1
ORDER BY CD_PRODUTO
`

const CONTRATOS = (ID_ENTIDADE) => `
SELECT
    C.ID_CONTRATO AS ID,
    CONCAT(C.CD_CONTRATO, ' - ', P.NM_PESSOA) AS DS,
    C.ID_PESSOA
FROM CONTRATOS C
    INNER JOIN PESSOAS P ON C.ID_PESSOA = P.ID_PESSOA
WHERE C.ID_ENTIDADE = ${ID_ENTIDADE} AND C.CD_STATUS = 'A'
`

module.exports = {
    CIDADES,
    PESSOAS,
    CONTRATOS,
    CATEGORIAS_PRODUTOS,
    CATEGORIAS_ESTOQUE,
    CATEGORIA_FINANCEIRO,
    CATEGORIA_MOVIMENTACAO,
    PRODUTOS_MATERIAL,
    PRODUTOS_ESTOQUE,
    PRODUTOS_MOVIMENTACAO
}