const PESSOAS = (ID_ENTIDADE) => `
SELECT
    ID_PESSOA AS ID,
    CONCAT(CD_PESSOA, ' - ', NM_PESSOA, ' - ', CADASTRO) AS DS
FROM PESSOAS
    WHERE ID_ENTIDADE = ${ID_ENTIDADE}
    AND SN_ATIVO = 1
ORDER BY CD_PESSOA`

const PRODUTOS = (ID_ENTIDADE) => `
SELECT
    ID_PRODUTO AS ID,
    CONCAT(
        CD_PRODUTO, ' - ',
        NM_PRODUTO, ' - ',
        UN_MEDIDA, ' - ',
        COALESCE(CD_BARRAS, '')) AS DS,
    VL_PRODUTO AS VL_VENDA_PRODUTO
FROM PRODUTOS
    WHERE ID_ENTIDADE = ${ID_ENTIDADE}
    AND SN_ATIVO = 1
ORDER BY CD_PRODUTO
`

const CLIENTE_PADRAO = (ID_ENTIDADE) => `
SELECT
    ID_CLIENTE_PADRAO AS ID_PESSOA
FROM ENTIDADES
    WHERE ID_ENTIDADE = ${ID_ENTIDADE}
`


module.exports = {
    PESSOAS,
    PRODUTOS,
    CLIENTE_PADRAO
}