const PESSOAS = (ID_ENTIDADE) => `
SELECT
    ID_PESSOA AS ID,
    CONCAT(CD_PESSOA, ' - ', NM_PESSOA, ' - ', CADASTRO) AS DS
FROM PESSOAS
    WHERE ID_ENTIDADE = ${ID_ENTIDADE}
    AND SN_ATIVO = 1
ORDER BY CD_PESSOA`

const PRODUTOS = (ID_ENTIDADE) => `
SELECT
    ID_PRODUTO AS ID,
    CONCAT(CD_PRODUTO, ' - ', NM_PRODUTO, ' - ', UN_MEDIDA) AS DS
FROM PRODUTOS
    WHERE ID_ENTIDADE = ${ID_ENTIDADE}
    AND SN_ATIVO = 1
ORDER BY CD_PRODUTO
`


module.exports = {
    PESSOAS,
    PRODUTOS
}